// Product catalogue — bougies fleuries
const SOMA_PRODUCTS = [
  {
    id: "rose-de-mai",
    name: "Rose de Mai",
    subtitle: "Bougie fleurie · cire de soja",
    price: 48,
    blurb:
      "Une couronne de pétales de rose ancienne, séchés à la main dans notre atelier de Grasse. Brûle 42 heures.",
    swatch: ["#d4a09a", "#e8c8b8", "#f3dcc8"],
    notes: ["Rose de mai", "Bois de santal", "Iris poudré"],
    sizes: [
      { label: "Petit · 180g", price: 48 },
      { label: "Moyen · 320g", price: 72 },
      { label: "Grand · 540g", price: 110 },
    ],
    scents: ["Rose poudrée", "Rose & oud", "Rose neutre"],
    placeholderLabel: "BOUGIE ROSE",
    photoTone: "rose",
    photo: "https://images.unsplash.com/photo-1603006905003-be475563bc59?w=900&q=80",
  },
  {
    id: "champ-de-camomille",
    name: "Champ de camomille",
    subtitle: "Bougie fleurie · cire d'abeille",
    price: 54,
    blurb: "Camomille romaine et marguerites des champs, cueillies en Drôme provençale. Une lumière dorée, une odeur d'été.",
    swatch: ["#e8d28a", "#f1e0a8", "#fbf0c8"],
    notes: ["Camomille", "Foin coupé", "Miel d'acacia"],
    sizes: [{ label: "Petit · 180g", price: 54 }, { label: "Moyen · 320g", price: 78 }],
    scents: ["Camomille pure", "Camomille & miel"],
    placeholderLabel: "CAMOMILLE",
    photoTone: "butter",
  },
  {
    id: "lavande-haute",
    name: "Lavande haute",
    subtitle: "Bougie fleurie · cire de soja",
    price: 46,
    blurb: "Lavande fine de Sault, brins entiers couchés dans la cire. Pour les soirées qui demandent du calme.",
    swatch: ["#a39bc0", "#c4b8d4", "#ddd2e3"],
    notes: ["Lavande fine", "Romarin", "Cèdre blanc"],
    sizes: [{ label: "Petit · 180g", price: 46 }, { label: "Moyen · 320g", price: 70 }, { label: "Grand · 540g", price: 105 }],
    scents: ["Lavande nature", "Lavande & cèdre"],
    placeholderLabel: "LAVANDE",
    photoTone: "lavender",
  },
  {
    id: "bouquet-aout",
    name: "Bouquet d'août",
    subtitle: "Édition limitée · cire végétale",
    price: 86,
    blurb: "Pivoine, achillée, statice, gypsophile. Le bouquet de fin d'été figé dans la cire — chaque pièce unique.",
    swatch: ["#c98a8a", "#e0a8a8", "#efc8c0"],
    notes: ["Pivoine", "Néroli", "Vétiver doux"],
    sizes: [{ label: "Moyen · 380g", price: 86 }, { label: "Grand · 620g", price: 138 }],
    scents: ["Bouquet original", "Pivoine seule"],
    placeholderLabel: "BOUQUET AOÛT",
    photoTone: "terracotta",
    badge: "Édition",
    photo: "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?w=900&q=80",
  },
  {
    id: "immortelle",
    name: "Immortelle",
    subtitle: "Bougie fleurie · cire de soja",
    price: 52,
    blurb: "Hélichryse de Corse, jaune soufre. Tient des mois sans se faner — la fleur, comme la mémoire qu'elle évoque.",
    swatch: ["#d4b860", "#e4cd84", "#f0dfa8"],
    notes: ["Immortelle", "Romarin", "Cuir blond"],
    sizes: [{ label: "Petit · 180g", price: 52 }, { label: "Moyen · 320g", price: 76 }],
    scents: ["Immortelle pure", "Immortelle & cuir"],
    placeholderLabel: "IMMORTELLE",
    photoTone: "ochre",
  },
  {
    id: "eucalyptus-blanc",
    name: "Eucalyptus blanc",
    subtitle: "Bougie fleurie · cire de soja",
    price: 44,
    blurb: "Branches d'eucalyptus poudré et fleurs de coton. Une bougie pour la chambre, pour respirer.",
    swatch: ["#a8b8a8", "#c4d0c0", "#dde3d8"],
    notes: ["Eucalyptus", "Coton", "Mousse blanche"],
    sizes: [{ label: "Petit · 180g", price: 44 }, { label: "Moyen · 320g", price: 68 }],
    scents: ["Eucalyptus frais", "Coton doux"],
    placeholderLabel: "EUCALYPTUS",
    photoTone: "sage",
  },
  {
    id: "rose-blanche",
    name: "Rose blanche",
    subtitle: "Bougie fleurie · cire de soja",
    price: 50,
    blurb: "Une seule rose blanche, entière, au cœur de la cire. Pour les déclarations silencieuses.",
    swatch: ["#ece7e0", "#d8d0c5", "#bcb1a3"],
    notes: ["Rose blanche", "Musc blanc", "Vanille bourbon"],
    sizes: [{ label: "Petit · 180g", price: 50 }, { label: "Moyen · 320g", price: 74 }],
    scents: ["Rose blanche", "Rose & vanille"],
    placeholderLabel: "ROSE BLANCHE",
    photoTone: "cream",
    photo: "https://images.unsplash.com/photo-1495231916356-a86217efff12?w=900&q=80",
  },
  {
    id: "pivoine-rose",
    name: "Pivoine rose",
    subtitle: "Bougie fleurie · cire végétale",
    price: 58,
    blurb: "Pivoines roses cueillies en Anjou. La fleur la plus généreuse de mai, figée à son apogée.",
    swatch: ["#dca4a4", "#e8bcb8", "#f4d4d0"],
    notes: ["Pivoine", "Pêche blanche", "Bois flotté"],
    sizes: [{ label: "Petit · 200g", price: 58 }, { label: "Moyen · 360g", price: 86 }, { label: "Grand · 580g", price: 124 }],
    scents: ["Pivoine fraîche", "Pivoine & pêche"],
    placeholderLabel: "PIVOINE",
    photoTone: "rose",
  },
  {
    id: "tournesol",
    name: "Tournesol miniature",
    subtitle: "Bougie fleurie · cire d'abeille",
    price: 42,
    blurb: "Petits soleils nains, ramassés tard en saison. Une bougie qui réchauffe les jours gris.",
    swatch: ["#e0a838", "#ecc06c", "#f4d898"],
    notes: ["Tournesol", "Foin", "Caramel blond"],
    sizes: [{ label: "Petit · 180g", price: 42 }, { label: "Moyen · 320g", price: 66 }],
    scents: ["Tournesol nature", "Tournesol & miel"],
    placeholderLabel: "TOURNESOL",
    photoTone: "ochre",
  },
  {
    id: "fleurs-sechees-mix",
    name: "Mélange séché",
    subtitle: "Édition atelier · pièce unique",
    price: 78,
    blurb: "Statice, gypsophile, achillée, lavande. Composition libre, jamais deux pareilles.",
    swatch: ["#c0a89c", "#d8c0b4", "#ecd8c8"],
    notes: ["Fleurs séchées", "Foin", "Bois doux"],
    sizes: [{ label: "Moyen · 360g", price: 78 }, { label: "Grand · 580g", price: 118 }],
    scents: ["Composition mixte", "Foin & bois"],
    placeholderLabel: "MÉLANGE SÉCHÉ",
    photoTone: "dusk",
    badge: "Pièce unique",
    photo: "https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=900&q=80",
  },
  {
    id: "muguet-mai",
    name: "Muguet du 1er mai",
    subtitle: "Édition saisonnière · cire de soja",
    price: 56,
    blurb: "Muguet de pleine terre, cueilli le matin du 1er mai. Édition d'une seule semaine.",
    swatch: ["#d4dcc8", "#e4eadc", "#f0f4e8"],
    notes: ["Muguet", "Verveine", "Mousse fraîche"],
    sizes: [{ label: "Petit · 180g", price: 56 }],
    scents: ["Muguet pur"],
    placeholderLabel: "MUGUET",
    photoTone: "sage",
    badge: "Saison",
  },
  {
    id: "violette",
    name: "Violette de Toulouse",
    subtitle: "Bougie fleurie · cire de soja",
    price: 48,
    blurb: "Violettes de Toulouse, parfum d'enfance et de bonbons d'autrefois.",
    swatch: ["#9c8cb8", "#b8a8cc", "#d4c8e0"],
    notes: ["Violette", "Iris", "Sucre cuit"],
    sizes: [{ label: "Petit · 180g", price: 48 }, { label: "Moyen · 320g", price: 72 }],
    scents: ["Violette pure", "Violette & iris"],
    placeholderLabel: "VIOLETTE",
    photoTone: "lavender",
  },
  {
    id: "souci-orange",
    name: "Souci orange",
    subtitle: "Bougie fleurie · cire de soja",
    price: 44,
    blurb: "Calendula et souci des jardins. Orange brûlé, lumière de fin d'après-midi.",
    swatch: ["#dc8050", "#e8a078", "#f0c0a0"],
    notes: ["Calendula", "Cuir tanné", "Tabac blond"],
    sizes: [{ label: "Petit · 180g", price: 44 }, { label: "Moyen · 320g", price: 68 }],
    scents: ["Souci nature", "Souci & cuir"],
    placeholderLabel: "SOUCI",
    photoTone: "terracotta",
  },
  {
    id: "trio-decouverte",
    name: "Trio découverte",
    subtitle: "Coffret · 3 mini bougies 60g",
    price: 64,
    blurb: "Trois petites bougies pour découvrir : Rose de mai, Lavande haute, Eucalyptus blanc. Coffret cadeau.",
    swatch: ["#d4a09a", "#a39bc0", "#a8b8a8"],
    notes: ["Découverte", "Multi-floral"],
    sizes: [{ label: "Coffret 3×60g", price: 64 }],
    scents: ["Mix classique", "Mix doux", "Mix fleuri"],
    placeholderLabel: "COFFRET TRIO",
    photoTone: "cream",
    badge: "Cadeau",
  },
  {
    id: "table-dressee",
    name: "Table dressée",
    subtitle: "Édition mariage · 8 bougies fleuries",
    price: 220,
    blurb: "Huit bougies coordonnées pour une table de huit convives. Fleurs au choix.",
    swatch: ["#d4a09a", "#e8c8b8", "#c98a8a"],
    notes: ["Sur-mesure", "Multi-fleur"],
    sizes: [{ label: "Coffret 8 pièces", price: 220 }, { label: "Coffret 12 pièces", price: 320 }],
    scents: ["Au choix"],
    placeholderLabel: "TABLE 8",
    photoTone: "rose",
    badge: "Mariage",
    photo: "https://images.unsplash.com/photo-1576020799627-aeac74d58064?w=900&q=80",
  },
  {
    id: "rose-noire",
    name: "Rose noire",
    subtitle: "Édition limitée · cire végétale",
    price: 68,
    blurb: "Roses bordeaux profondes, presque noires. Une bougie sombre, pour les nuits longues.",
    swatch: ["#5a3a3a", "#7e4848", "#a06868"],
    notes: ["Rose noire", "Patchouli", "Encens fumé"],
    sizes: [{ label: "Moyen · 320g", price: 68 }, { label: "Grand · 540g", price: 108 }],
    scents: ["Rose noire", "Rose & encens"],
    placeholderLabel: "ROSE NOIRE",
    photoTone: "dusk",
    badge: "Édition",
  },
  {
    id: "carte-cadeau",
    name: "Carte cadeau",
    subtitle: "Bon d'achat · papier filigrane",
    price: 50,
    blurb: "Une carte manuscrite, glissée dans une enveloppe de papier ciré. Valable un an.",
    swatch: ["#ece1cc", "#d4c5a8", "#bca989"],
    notes: ["Cadeau", "Manuscrite"],
    sizes: [{ label: "50€", price: 50 }, { label: "100€", price: 100 }, { label: "200€", price: 200 }],
    scents: ["—"],
    placeholderLabel: "CARTE CADEAU",
    photoTone: "cream",
  },
  {
    id: "recharge-rose",
    name: "Recharge — rose",
    subtitle: "Recharge · sans contenant",
    price: 32,
    blurb: "Pour ceux qui gardent leur photophore Soma. Cire fleurie, 320g, à fondre.",
    swatch: ["#d4a09a", "#e8c8b8", "#f3dcc8"],
    notes: ["Recharge", "Rose"],
    sizes: [{ label: "320g", price: 32 }, { label: "540g", price: 48 }],
    scents: ["Rose poudrée"],
    placeholderLabel: "RECHARGE",
    photoTone: "rose",
    badge: "Recharge",
  },
];

window.SOMA_PRODUCTS = SOMA_PRODUCTS;
